### ISSUE TITLE
Fresh install doesn't work due to old numpy version

### ISSUE THREAD

**Issue by mikix** [Machine-Learning-for-Medical-Language/cnlp_transformers#85]
The pinning of run time dependencies is pretty tight. If I do the following on a fresh system:

```
pip install cnlp-transformers
python3 -m cnlpt.train_system
```

I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/cnlp_transformers/src/cnlpt/__init__.py", line 1, in <module>
    import nltk as _nltk
  File "/usr/local/lib/python3.10/dist-packages/nltk/__init__.py", line 145, in <module>
    from nltk.chunk import *
  File "/usr/local/lib/python3.10/dist-packages/nltk/chunk/__init__.py", line 155, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/usr/local/lib/python3.10/dist-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.chunk.util import ChunkScore
  File "/usr/local/lib/python3.10/dist-packages/nltk/chunk/util.py", line 12, in <module>
    from nltk.tag.mapping import map_tag
  File "/usr/local/lib/python3.10/dist-packages/nltk/tag/__init__.py", line 70, in <module>
    from nltk.tag.sequential import (
  File "/usr/local/lib/python3.10/dist-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/usr/local/lib/python3.10/dist-packages/nltk/classify/__init__.py", line 97, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/usr/local/lib/python3.10/dist-packages/nltk/classify/scikitlearn.py", line 38, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/usr/local/lib/python3.10/dist-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/__init__.py", line 22, in <module>
    from .murmurhash import murmurhash3_32
  File "sklearn/utils/murmurhash.pyx", line 1, in init sklearn.utils.murmurhash
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Looks like sklearn doesn't like the older numpy version used.

You can work around this by doing `pip3 install --force-reinstall sklearn` which will then install a newer numpy. And things seem to work a bit. But then we're out of compliance with what cnlp_transformers requests (which at time of writing is `numpy~=1.21.5`)

So I guess we need to either tighten even further, so we get a lower version of `sklearn` or loosen up a bit to allow newer numpy (and other deps why not). The current dependency specs do seem unusually tight (I'm used to seeing more `>=` signs rather than `~=` signs)

**Comment by angus-lherrou** [comment]
Hi Michael--what is your OS and system architecture?

**Comment by mikix** [comment]
I was testing this on amd64 ubuntu 22.04.

**Comment by angus-lherrou** [comment]
Thanks. I just did some testing myself and this appears to be an issue with the Python 3.10 builds of those package versions. I will continue to investigate this, but for now, you should be able to use Python 3.9 or 3.8 as a workaround.

**Comment by angus-lherrou** [comment]
FYI, I've added some automated tests via GitHub Actions that should catch this sort of thing in the future. We've been using the current package version on existing virtual environments (with presumably older compatible dependencies) without issue, which is why we missed this. We will be updating the package to a new version within the next few weeks, but I will attempt to get a patch version out by the end of next week to address the current problems with a fresh install.

**Comment by angus-lherrou** [comment]
The reason we have the dependencies pinned tightly is because of issues like #88, where a dependency will randomly break something in our code with a new release. Normally you can rely on semantic versioning to guard against this, but not everyone does that well, so we try to pin things to minor releases. Naturally, the one package we didn't pin at a minor release or tighter (`transformers`) broke this.

Once I fix #88 I will look into updating our pinned ranges for numpy and scikit-learn.

**Comment by angus-lherrou** [comment]
It seems the problem is that scikit-learn 0.24 does not pin a numpy version in its build dependencies for Python 3.10, since it only explicitly supports Python 3.7-3.9. Going to look into upgrading scikit-learn to a newer version that officially supports Python 3.10.

We are stuck with numpy 1.21 for the time being because it does not support Python 3.7.
